<a href="https://colab.research.google.com/github/basanivreddy/Calorieburn-Prediction/blob/main/Welcome_to_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.26.4


In [8]:
import keras
print(keras.__version__)

3.5.0


In [9]:
import tensorflow as tf
print(tf.__version__)

2.17.1


In [22]:
import numpy as np
a = [1,2,3,4,5]
a_numpy = np.array(a)
#Print an array
a_numpy

array([1, 2, 3, 4, 5])

In [14]:
import numpy as np

c = [(1, 2), [3, 4, (5)], (6, 7, 8)]
b = np.array(c,dtype=object)
print(b)
print(b.shape)

[(1, 2) list([3, 4, 5]) (6, 7, 8)]
(3,)


In [11]:
import numpy as np

c = [(1, 2), [3, 4, (5)], (6, 7, 8)]
b = np.asarray(c, dtype=object)
print(b)
print(b.shape)


[(1, 2) list([3, 4, 5]) (6, 7, 8)]
(3,)


In [19]:
a = (1,2,3)
c=([1,2,3,4],4,5)
b = np.asarray(a, dtype=object)
d = np.asarray(c, dtype=object)
print(b)

[1 2 3]


In [20]:

a = (1,2,3)
c=([1,2,3,4],4,5)
b = np.asarray(a, dtype=object)
d = np.asarray(c, dtype=object)
b

array([1, 2, 3], dtype=object)

In [25]:
a = np.zeros((5,4), dtype = np.float16)
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float16)

In [28]:
a = np.full((3,3),2,dtype=np.int32)
a


array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]], dtype=int32)

In [26]:
np.linspace(1,5,num=5,endpoint=True,retstep=True)


(array([1., 2., 3., 4., 5.]), 1.0)

In [30]:
np.arange(start=5,stop=100,step=7)

array([ 5, 12, 19, 26, 33, 40, 47, 54, 61, 68, 75, 82, 89, 96])

In [34]:
import tensorflow as tf
print(tf.math.add(1., 2.))
print(tf.math.add([1, 2], [3, 4]))
print(tf.math.square(5))
print(tf.math.reduce_sum([1, 2, 3]))
print(tf.math.square(5)+tf.math.square(6))
print(tf.math.square(2) + tf.math.square(3))


tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(61, shape=(), dtype=int32)
tf.Tensor(13, shape=(), dtype=int32)


In [35]:
x = tf.linalg.matmul([[2]], [[2, 3]])
print(x)
print(x.shape)
print(x.dtype)


tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)
(1, 2)
<dtype: 'int32'>


In [40]:
from tensorflow.keras.layers import TextVectorization
training_data = np.array([["This is hi vivek"], ["this is hello lab"]])
training_data
vectorizer = TextVectorization(output_mode="int")
vectorizer.adapt(training_data)
integer_data = vectorizer(training_data)
print(integer_data)

tf.Tensor(
[[2 3 6 4]
 [2 3 7 5]], shape=(2, 4), dtype=int64)


In [41]:
import numpy as np
from tensorflow.keras.layers import CenterCrop, Rescaling
from PIL import Image

# Load an image
image_path = "/content/viv.jpg"  # Replace with the actual path to your image
image = Image.open(image_path)   # Load the image
image = image.resize((200, 200))  # Resize to match the expected input size

# Convert the image to a NumPy array
image_array = np.array(image).astype("float32")  # Shape: (200, 200, 3)

# Add a batch dimension (batch_size=1)
image_batch = np.expand_dims(image_array, axis=0)  # Shape: (1, 200, 200, 3)

# Define the CenterCrop and Rescaling layers
cropper = CenterCrop(height=100, width=100)
scaler = Rescaling(scale=1.0 / 255)

# Apply cropping and scaling
output_data = scaler(cropper(image_batch))

# Print results
print("shape:", output_data.shape)  # Expected shape: (1, 100, 100, 3)
print("min:", np.min(output_data))  # Minimum pixel value, scaled
print("max:", np.max(output_data))  # Maximum pixel value, scaled
print(output_data)

shape: (1, 100, 100, 3)
min: 0.0
max: 1.0
tf.Tensor(
[[[[1.         0.97647065 0.9568628 ]
   [0.9843138  0.9803922  0.9607844 ]
   [0.9607844  0.9686275  0.9607844 ]
   ...
   [0.69803923 0.63529414 0.54509807]
   [0.7019608  0.6392157  0.54901963]
   [0.7019608  0.6392157  0.54901963]]

  [[1.         0.9803922  0.95294124]
   [0.98823535 0.9803922  0.95294124]
   [0.9607844  0.96470594 0.9490197 ]
   ...
   [0.7019608  0.6392157  0.54901963]
   [0.7019608  0.6392157  0.54901963]
   [0.7019608  0.6392157  0.54901963]]

  [[0.9960785  0.96470594 0.9294118 ]
   [0.97647065 0.96470594 0.9294118 ]
   [0.9450981  0.95294124 0.9294118 ]
   ...
   [0.7176471  0.654902   0.5647059 ]
   [0.7137255  0.6509804  0.56078434]
   [0.70980394 0.64705884 0.5568628 ]]

  ...

  [[0.454902   0.4156863  0.37647063]
   [0.46274513 0.42352945 0.38431376]
   [0.47058827 0.43137258 0.38823533]
   ...
   [0.43529415 0.454902   0.3647059 ]
   [0.4431373  0.46274513 0.37254903]
   [0.454902   0.47450984 0.3843

In [42]:
from tensorflow.keras.layers import CenterCrop
from tensorflow.keras.layers import Rescaling

# Example image data, with values in the [0, 255] range
training_data = np.random.randint(0, 256, size=(64, 200, 200, 3)).astype("float32")

cropper = CenterCrop(height=100, width=100)
scaler = Rescaling(scale=1.0 / 255)

output_data = scaler(cropper(training_data))
print("shape:", output_data.shape)
print("min:", np.min(output_data))
print("max:", np.max(output_data))

shape: (64, 100, 100, 3)
min: 0.0
max: 1.0


In [45]:
import torch
x = torch.rand(2, 3)  # An un-initialized Tensor object. x holds garbage data.
y = torch.rand(2, 3)    # Initialize with random values

# Operations

z1 = x + y
z2 = torch.add(x, y)             # Same as above

print(z2)

tensor([[0.8466, 1.3614, 0.9879],
        [1.0975, 0.9514, 1.3637]])


In [46]:
import torch
x = torch.Tensor(2, 3)  # An un-initialized Tensor object. x holds garbage data.
y = torch.Tensor(2, 3)    # Initialize with random values
# Operations
z1 = x + y
z2 = torch.add(x, y)             # Same as above
print(z2)

tensor([[-7.5685e-32,  8.7632e-41,  7.1812e-29],
        [ 0.0000e+00,  2.4984e-01,  5.7574e-01]])
